---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: github_binary_release
  image: husseingalal/drone-dispatch:v0.0.5
  settings:
    repo: 'k3s-upgrade-action-test'
    owner: 'galal-hussein'
    api_key:
      from_secret: github_token
    event_type: "build"
    client_data: '{"tag":"test","checksum": "test"}'
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
