---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: github_binary_release
  image: galal-hussein/drone-dispatch:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    event_type: "build"
    client_data: '{"tag":"test","checksum": "1234"}'
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
